
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ITEM_ST NEWLINE OL_EN OL_ST TEXT UL_EN UL_STul : UL_ST list UL_ENol : OL_ST list OL_ENlist : list listitem\n\t\t\t\t| listitemlistitem : ITEM_ST TEXT'
    
_lr_action_items = {'TEXT':([3,],[6,]),'UL_ST':([0,],[2,]),'ITEM_ST':([2,4,5,6,8,],[3,3,-4,-5,-3,]),'UL_EN':([4,5,6,8,],[7,-4,-5,-3,]),'$end':([1,7,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ul':([0,],[1,]),'list':([2,],[4,]),'listitem':([2,4,],[5,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ul","S'",1,None,None,None),
  ('ul -> UL_ST list UL_EN','ul',3,'p_ul','latex-parser.py',21),
  ('ol -> OL_ST list OL_EN','ol',3,'p_ol','latex-parser.py',27),
  ('list -> list listitem','list',2,'p_list','latex-parser.py',33),
  ('list -> listitem','list',1,'p_list','latex-parser.py',34),
  ('listitem -> ITEM_ST TEXT','listitem',2,'p_listitem','latex-parser.py',37),
]
